apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: rest-cxfrs-service
spec:
  hosts:
  - rest-cxfrs-service
  http:
  - fault:
      abort:
        httpStatus: 500
        percent: 100
    match:
    - headers:
        magic-word:
          exact: breakit
    route:
    - destination:
        host: rest-cxfrs-service
  - route:
    - destination:
        host: rest-cxfrs-service
