apiVersion: admin.enmasse.io/v1beta1
kind: StandardInfraConfig
metadata:
  name: default-minimal
  labels:
    app: enmasse
spec:
  version: 0.26-SNAPSHOT
  admin:
    resources:
      memory: 512Mi
  broker:
    resources:
      memory: 1Gi
      storage: 2Gi
    addressFullPolicy: FAIL
  router:
    minReplicas: 1
    resources:
      memory: 512Mi
    linkCapacity: 250
